### ISSUE TITLE
Queries always end in error

### ISSUE THREAD

**Issue by jannikscho** [openAIP/openaip#11]
I tested the different endpoints. 
I noticed that all requests are answered with error 500 or 503.
After several attempts you may get a correct answer.
For 71 airport-requests, only one result was returned with a FeatureList,
the other responses were Error 500 or 503.

This is my Request (The ApiKey was cut off and filled with X):
https://staging.api.openaip.net/api/v2/airports?apiKey=2NaCL8jtkvqdIDlXXXXXXXXXXXXXXXXXXXXXXXX&country=DE&page=1.

In the past (beginning of the year) it worked as expected.
What am I doing wrong?

**Comment by reskume** [comment]
The current staging system is a work in progress. Although the endpoints for airports and airspaces are "available" they currently don't work since the backend needs refactoring in those particular parts. 

As soon as the "data" sections on the webpage shows the content types, the API should be working again too. Can you please try with endpoints for hotspots/navaids? They should work...

**Comment by jannikscho** [comment]
Thank you for your prompt reply.
I can confirm that the hotspots and navaids work as expected.

**Comment by reskume** [comment]
OK. I'll leave this open and as soon as new version with the updated endpoints is available, I'll close this issue.

**Comment by reskume** [comment]
With upcoming beta release of the new version 2, most endpoints have changed but work as expected. See API documentation for updated API specification.

**Comment by Pol52** [comment]
I still can't query using the params indicated in the documentation. Seems like I can only use `fields` and `country`, but for some reason I can only get DE data.

Is it expected at the current stage of development? Thanks  :)
